version: '3.8'
services:
  envetia-myd-landing:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: envetia-myd-landing
    networks:
      - default
    environment:
      - VIRTUAL_HOST=envetia-myd.djcrespo.dev
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=envetia-myd.djcrespo.dev
    expose:
      - 80

networks:
  default:
    external:
      name: net-proxy
